/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.atm.app.gui;

// import org.junit.jupiter.api.Test;

// import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
}
